Fetching departments for municipality ID: 2
Fetching departments for municipality ID: 2
Watching for file changes with StatReloader
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Not Found: /favicon.ico
Fetching departments for municipality ID: 2
Fetching departments for municipality ID: 2
Fetching departments for municipality ID: 2
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Method Not Allowed (GET): /logout/
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Fetching departments for municipality ID: 2
Not Found: /departments/3/grievance/
Not Found: /departments/3/feedback/
Fetching departments for municipality ID: 2
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Not Found: /accounts/profile/
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Fetching departments for municipality ID: 2
Internal Server Error: /departments/3/grievance/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: base_grievance.updated

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\base\views.py", line 88, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\edit.py", line 133, in form_valid
    self.object = form.save()
                  ^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\forms\models.py", line 554, in save
    self.instance.save()
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: base_grievance.updated
Watching for file changes with StatReloader
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Not Found: /favicon.ico
Method Not Allowed (GET): /logout/
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Fetching departments for municipality ID: 1
Internal Server Error: /departments/1/feedback/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: base_feedback.updated

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\base\views.py", line 66, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\edit.py", line 133, in form_valid
    self.object = form.save()
                  ^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\forms\models.py", line 554, in save
    self.instance.save()
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: base_feedback.updated
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Fetching departments for municipality ID: 1
Internal Server Error: /departments/1/feedback/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: base_feedback.updated

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\base\views.py", line 66, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\edit.py", line 133, in form_valid
    self.object = form.save()
                  ^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\forms\models.py", line 554, in save
    self.instance.save()
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: base_feedback.updated
Fetching departments for municipality ID: 1
Internal Server Error: /departments/1/grievance/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: base_grievance.updated

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\base\views.py", line 88, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\edit.py", line 133, in form_valid
    self.object = form.save()
                  ^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\forms\models.py", line 554, in save
    self.instance.save()
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: base_grievance.updated
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Not Found: /accounts/profile/
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Forbidden (Permission denied): /grievances/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 108, in dispatch
    return self.handle_no_permission()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 48, in handle_no_permission
    raise PermissionDenied(self.get_permission_denied_message())
django.core.exceptions.PermissionDenied
Internal Server Error: /admin/base/grievance/add/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: base_grievance.updated

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\admin\options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\admin\sites.py", line 246, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\admin\options.py", line 1984, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\admin\options.py", line 1843, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\admin\options.py", line 1894, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\admin\options.py", line 1314, in save_model
    obj.save()
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: base_grievance.updated
C:\Cosmic\Project\FeedbackAndGrievance\base\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\models.py changed, reloading.
Watching for file changes with StatReloader
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'Logout' not found. 'Logout' is not a valid view function or pattern name.
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Method Not Allowed (GET): /logout/
Method Not Allowed (GET): /logout/
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home.logout' not found. 'home.logout' is not a valid view function or pattern name.
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Not Found: /accounts/profile/
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Forbidden (Permission denied): /grievances/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 108, in dispatch
    return self.handle_no_permission()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 48, in handle_no_permission
    raise PermissionDenied(self.get_permission_denied_message())
django.core.exceptions.PermissionDenied
Forbidden (Permission denied): /grievances/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 108, in dispatch
    return self.handle_no_permission()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 48, in handle_no_permission
    raise PermissionDenied(self.get_permission_denied_message())
django.core.exceptions.PermissionDenied
Not Found: /grievances/
Not Found: /grievances/
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Not Found: /accounts/profile/
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Internal Server Error: /grievances/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\urls\base.py", line 81, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'egovernance'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\urls\base.py", line 92, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'egovernance' is not a registered namespace
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Not Found: /accounts/profile/
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Internal Server Error: /grievances/1/status/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: base/grievance_status_form.html
Internal Server Error: /grievances/1/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: base/grievance_detail.html
Forbidden (Permission denied): /grievances/1/respond/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 108, in dispatch
    return self.handle_no_permission()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 48, in handle_no_permission
    raise PermissionDenied(self.get_permission_denied_message())
django.core.exceptions.PermissionDenied
Internal Server Error: /grievances/1/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: base/grievance_detail.html
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Fetching departments for municipality ID: 1
Forbidden (Permission denied): /departments/1/grievance/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 108, in dispatch
    return self.handle_no_permission()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 48, in handle_no_permission
    raise PermissionDenied(self.get_permission_denied_message())
django.core.exceptions.PermissionDenied
Forbidden (Permission denied): /departments/1/feedback/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 108, in dispatch
    return self.handle_no_permission()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 48, in handle_no_permission
    raise PermissionDenied(self.get_permission_denied_message())
django.core.exceptions.PermissionDenied
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Watching for file changes with StatReloader
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Not Found: /favicon.ico
Internal Server Error: /grievances/1/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: base/grievance_detail.html
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Not Found: /accounts/profile/
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Fetching departments for municipality ID: 1
Fetching departments for municipality ID: 1
Fetching departments for municipality ID: 1
Watching for file changes with StatReloader
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Not Found: /favicon.ico
Not Found: /accounts/profile/
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Internal Server Error: /grievances/1/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: base/grievance_detail.html
Internal Server Error: /grievances/1/status/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: base/grievance_status_form.html
Forbidden (Permission denied): /grievances/1/respond/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 108, in dispatch
    return self.handle_no_permission()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 48, in handle_no_permission
    raise PermissionDenied(self.get_permission_denied_message())
django.core.exceptions.PermissionDenied
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Not Found: /favicon.ico
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Not Found: /accounts/profile/
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Forbidden (Permission denied): /grievances/1/respond/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 108, in dispatch
    return self.handle_no_permission()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 48, in handle_no_permission
    raise PermissionDenied(self.get_permission_denied_message())
django.core.exceptions.PermissionDenied
Internal Server Error: /grievances/1/status/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: base/grievance_status_form.html
Internal Server Error: /grievances/1/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: base/grievance_detail.html
Internal Server Error: /grievances/1/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: base/grievance_detail.html
Fetched states: <QuerySet [<State: Bagmati Province>, <State: Gandaki Province>, <State: Karnali Province>, <State: Koshi Province>, <State: Lumbini Province>, <State: Madhesh Province>, <State: Sudurpaschim Province>]>
Fetching departments for municipality ID: 2
Forbidden (Permission denied): /departments/3/feedback/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 108, in dispatch
    return self.handle_no_permission()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 48, in handle_no_permission
    raise PermissionDenied(self.get_permission_denied_message())
django.core.exceptions.PermissionDenied
C:\Cosmic\Project\FeedbackAndGrievance\base\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\models.py changed, reloading.
Watching for file changes with StatReloader
Forbidden (Permission denied): /departments/3/feedback/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 108, in dispatch
    return self.handle_no_permission()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 48, in handle_no_permission
    raise PermissionDenied(self.get_permission_denied_message())
django.core.exceptions.PermissionDenied
Not Found: /favicon.ico
Fetched states: ['Bagmati Province', 'Gandaki Province', 'Karnali Province', 'Koshi Province', 'Lumbini Province', 'Madhesh Province', 'Sudurpaschim Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Fetching departments for municipality ID: 2
Fetched states: ['Bagmati Province', 'Gandaki Province', 'Karnali Province', 'Koshi Province', 'Lumbini Province', 'Madhesh Province', 'Sudurpaschim Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Fetched states: ['Bagmati Province', 'Gandaki Province', 'Karnali Province', 'Koshi Province', 'Lumbini Province', 'Madhesh Province', 'Sudurpaschim Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Not Found: /accounts/profile/
Fetched states: ['Bagmati Province', 'Gandaki Province', 'Karnali Province', 'Koshi Province', 'Lumbini Province', 'Madhesh Province', 'Sudurpaschim Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Fetching departments for municipality ID: 1
Fetched states: ['Bagmati Province', 'Gandaki Province', 'Karnali Province', 'Koshi Province', 'Lumbini Province', 'Madhesh Province', 'Sudurpaschim Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Fetching departments for municipality ID: 1
Fetching departments for municipality ID: 1
Fetched states: ['Bagmati Province', 'Gandaki Province', 'Karnali Province', 'Koshi Province', 'Lumbini Province', 'Madhesh Province', 'Sudurpaschim Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Not Found: /accounts/profile/
Fetched states: ['Bagmati Province', 'Gandaki Province', 'Karnali Province', 'Koshi Province', 'Lumbini Province', 'Madhesh Province', 'Sudurpaschim Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Fetching departments for municipality ID: 1
Feedback form context for department ID: 1
Saving feedback for user Saugat, department ID 1
Internal Server Error: /departments/1/feedback/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: base_feedback.updated

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\base\views.py", line 78, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\edit.py", line 133, in form_valid
    self.object = form.save()
                  ^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\forms\models.py", line 554, in save
    self.instance.save()
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: base_feedback.updated
Watching for file changes with StatReloader
Fetched states: ['Bagmati Province', 'Gandaki Province', 'Karnali Province', 'Koshi Province', 'Lumbini Province', 'Madhesh Province', 'Sudurpaschim Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Not Found: /favicon.ico
Fetched states: ['Bagmati Province', 'Gandaki Province', 'Karnali Province', 'Koshi Province', 'Lumbini Province', 'Madhesh Province', 'Sudurpaschim Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Fetching departments for municipality ID: 1
Fetched states: ['Bagmati Province', 'Gandaki Province', 'Karnali Province', 'Koshi Province', 'Lumbini Province', 'Madhesh Province', 'Sudurpaschim Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Not Found: /accounts/profile/
Fetched states: ['Bagmati Province', 'Gandaki Province', 'Karnali Province', 'Koshi Province', 'Lumbini Province', 'Madhesh Province', 'Sudurpaschim Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Fetching departments for municipality ID: 2
Feedback form context for department ID: 4
Saving feedback for user Saugat, department ID 4
Internal Server Error: /departments/4/feedback/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: base_feedback.updated

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\base\views.py", line 78, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\edit.py", line 133, in form_valid
    self.object = form.save()
                  ^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\forms\models.py", line 554, in save
    self.instance.save()
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: base_feedback.updated
C:\Cosmic\Project\FeedbackAndGrievance\base\models.py changed, reloading.
Watching for file changes with StatReloader
Fetched states: ['Bagmati Province', 'Gandaki Province', 'Karnali Province', 'Koshi Province', 'Lumbini Province', 'Madhesh Province', 'Sudurpaschim Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Feedback form context for department ID: 4
Fetched states: ['Bagmati Province', 'Gandaki Province', 'Karnali Province', 'Koshi Province', 'Lumbini Province', 'Madhesh Province', 'Sudurpaschim Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Internal Server Error: /admin/base/municipality/add/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: base_municipality.updated

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\admin\options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\admin\sites.py", line 246, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\admin\options.py", line 1984, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\admin\options.py", line 1843, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\admin\options.py", line 1894, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\admin\options.py", line 1314, in save_model
    obj.save()
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: base_municipality.updated
Internal Server Error: /admin/base/municipality/add/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: base_municipality.updated

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\admin\options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\admin\sites.py", line 246, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\admin\options.py", line 1984, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\utils\decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\utils\decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\admin\options.py", line 1843, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\admin\options.py", line 1894, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\admin\options.py", line 1314, in save_model
    obj.save()
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: base_municipality.updated
C:\Cosmic\Project\FeedbackAndGrievance\base\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\urls.py changed, reloading.
Watching for file changes with StatReloader
Forbidden (CSRF token from POST incorrect.): /departments/4/feedback/
C:\Cosmic\Project\FeedbackAndGrievance\base\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\FnG\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\FnG\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\FnG\settings.py changed, reloading.
Watching for file changes with StatReloader
Feedback form context for department ID: 4
Fetching departments for municipality ID: 2
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Not Found: /accounts/profile/
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Fetching departments for municipality ID: 1
Feedback form context for department ID: 1
Saving feedback for user Saugat, department ID 1, rating: 1
Fetching departments for municipality ID: 1
Grievance form context for department ID: 1
Saving grievance for user Saugat, department ID 1, title: Incompetent Management
Fetching departments for municipality ID: 1
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Not Found: /accounts/profile/
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Internal Server Error: /grievances/1/status/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: base/grievance_status_form.html
Forbidden (Permission denied): /grievances/1/respond/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 108, in dispatch
    return self.handle_no_permission()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 48, in handle_no_permission
    raise PermissionDenied(self.get_permission_denied_message())
django.core.exceptions.PermissionDenied
Forbidden (Permission denied): /grievances/2/respond/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 108, in dispatch
    return self.handle_no_permission()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 48, in handle_no_permission
    raise PermissionDenied(self.get_permission_denied_message())
django.core.exceptions.PermissionDenied
C:\Cosmic\Project\FeedbackAndGrievance\base\views.py changed, reloading.
Watching for file changes with StatReloader
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Grievances fetched for user Reman: [{'id': 1, 'title': 'Increase Budget', 'status': 'OPEN'}, {'id': 2, 'title': 'Incompetent Management', 'status': 'OPEN'}]
Grievance 1 details for user Reman: Increase Budget, Responses: []
Grievance status update form context for grievance ID: 1
Internal Server Error: /grievances/1/status/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: base/grievance_status_form.html
Forbidden (Permission denied): /grievances/1/respond/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 108, in dispatch
    return self.handle_no_permission()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 48, in handle_no_permission
    raise PermissionDenied(self.get_permission_denied_message())
django.core.exceptions.PermissionDenied
Grievances fetched for user Reman: [{'id': 1, 'title': 'Increase Budget', 'status': 'OPEN'}, {'id': 2, 'title': 'Incompetent Management', 'status': 'OPEN'}]
Grievance 2 details for user Reman: Incompetent Management, Responses: []
Forbidden (Permission denied): /grievances/2/respond/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 108, in dispatch
    return self.handle_no_permission()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 48, in handle_no_permission
    raise PermissionDenied(self.get_permission_denied_message())
django.core.exceptions.PermissionDenied
Grievance status update form context for grievance ID: 2
Internal Server Error: /grievances/2/status/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: base/grievance_status_form.html
C:\Cosmic\Project\FeedbackAndGrievance\base\views.py changed, reloading.
Watching for file changes with StatReloader
Forbidden (Permission denied): /grievances/2/respond/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 108, in dispatch
    return self.handle_no_permission()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\contrib\auth\mixins.py", line 48, in handle_no_permission
    raise PermissionDenied(self.get_permission_denied_message())
django.core.exceptions.PermissionDenied
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Not Found: /accounts/profile/
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Fetching departments for municipality ID: 2
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Fetching departments for municipality ID: 2
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Not Found: /accounts/profile/
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Grievances fetched for user Reman: [{'id': 1, 'title': 'Increase Budget', 'status': 'OPEN'}, {'id': 2, 'title': 'Incompetent Management', 'status': 'OPEN'}]
Grievance 1 details for user Reman: Increase Budget, Responses: []
Grievance response form context for grievance ID: 1
Saving grievance response for grievance ID 1 by user Reman, response: Pay your taxes lilbro
Grievance 1 details for user Reman: Increase Budget, Responses: [{'id': 1, 'response': 'Pay your taxes lilbro'}]
Grievance status update form context for grievance ID: 1
Updating grievance status for ID 1 to RESOLVED by user Reman
Grievance 1 details for user Reman: Increase Budget, Responses: [{'id': 1, 'response': 'Pay your taxes lilbro'}]
Grievances fetched for user Reman: [{'id': 1, 'title': 'Increase Budget', 'status': 'RESOLVED'}, {'id': 2, 'title': 'Incompetent Management', 'status': 'OPEN'}]
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Fetching departments for municipality ID: 2
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City')]
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
C:\Cosmic\Project\FeedbackAndGrievance\base\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\models.py changed, reloading.
Watching for file changes with StatReloader
Forbidden (CSRF token from POST incorrect.): /logout/
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(5, 'Dharan Sub-metropolitan City'), (1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City'), (3, 'Mahalaxmi Municipality'), (6, 'Hetauda Sub-metropolitan City'), (4, 'Pokhara Metropolitan City'), (8, 'Tulsipur Municipality'), (9, 'Godawari Municipality'), (10, 'Dhangadi Sub-metropolitan City'), (7, 'Birendranagar Municipality')]
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(5, 'Dharan Sub-metropolitan City'), (1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City'), (3, 'Mahalaxmi Municipality'), (6, 'Hetauda Sub-metropolitan City'), (4, 'Pokhara Metropolitan City'), (8, 'Tulsipur Municipality'), (9, 'Godawari Municipality'), (10, 'Dhangadi Sub-metropolitan City'), (7, 'Birendranagar Municipality')]
Not Found: /accounts/profile/
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(5, 'Dharan Sub-metropolitan City'), (1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City'), (3, 'Mahalaxmi Municipality'), (6, 'Hetauda Sub-metropolitan City'), (4, 'Pokhara Metropolitan City'), (8, 'Tulsipur Municipality'), (9, 'Godawari Municipality'), (10, 'Dhangadi Sub-metropolitan City'), (7, 'Birendranagar Municipality')]
Fetching departments for municipality ID: 5
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(5, 'Dharan Sub-metropolitan City'), (1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City'), (3, 'Mahalaxmi Municipality'), (6, 'Hetauda Sub-metropolitan City'), (4, 'Pokhara Metropolitan City'), (8, 'Tulsipur Municipality'), (9, 'Godawari Municipality'), (10, 'Dhangadi Sub-metropolitan City'), (7, 'Birendranagar Municipality')]
Fetching departments for municipality ID: 1
Feedback form context for department ID: 1
Fetching departments for municipality ID: 1
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(5, 'Dharan Sub-metropolitan City'), (1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City'), (3, 'Mahalaxmi Municipality'), (6, 'Hetauda Sub-metropolitan City'), (4, 'Pokhara Metropolitan City'), (8, 'Tulsipur Municipality'), (9, 'Godawari Municipality'), (10, 'Dhangadi Sub-metropolitan City'), (7, 'Birendranagar Municipality')]
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(5, 'Dharan Sub-metropolitan City'), (1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City'), (3, 'Mahalaxmi Municipality'), (6, 'Hetauda Sub-metropolitan City'), (4, 'Pokhara Metropolitan City'), (8, 'Tulsipur Municipality'), (9, 'Godawari Municipality'), (10, 'Dhangadi Sub-metropolitan City'), (7, 'Birendranagar Municipality')]
Not Found: /accounts/profile/
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(5, 'Dharan Sub-metropolitan City'), (1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City'), (3, 'Mahalaxmi Municipality'), (6, 'Hetauda Sub-metropolitan City'), (4, 'Pokhara Metropolitan City'), (8, 'Tulsipur Municipality'), (9, 'Godawari Municipality'), (10, 'Dhangadi Sub-metropolitan City'), (7, 'Birendranagar Municipality')]
Grievances fetched for user Reman: [{'id': 1, 'title': 'Increase Budget', 'status': 'RESOLVED'}, {'id': 2, 'title': 'Incompetent Management', 'status': 'OPEN'}]
Grievance 1 details for user Reman: Increase Budget, Responses: [{'id': 1, 'response': 'Pay your taxes lilbro'}]
Grievance response form context for grievance ID: 1
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(5, 'Dharan Sub-metropolitan City'), (1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City'), (3, 'Mahalaxmi Municipality'), (6, 'Hetauda Sub-metropolitan City'), (4, 'Pokhara Metropolitan City'), (8, 'Tulsipur Municipality'), (9, 'Godawari Municipality'), (10, 'Dhangadi Sub-metropolitan City'), (7, 'Birendranagar Municipality')]
Grievance 1 details for user admin: Increase Budget, Responses: [{'id': 1, 'response': 'Pay your taxes lilbro'}]
User admin not in Officials group
Not Found: /grievances/
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(5, 'Dharan Sub-metropolitan City'), (1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City'), (3, 'Mahalaxmi Municipality'), (6, 'Hetauda Sub-metropolitan City'), (4, 'Pokhara Metropolitan City'), (8, 'Tulsipur Municipality'), (9, 'Godawari Municipality'), (10, 'Dhangadi Sub-metropolitan City'), (7, 'Birendranagar Municipality')]
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(5, 'Dharan Sub-metropolitan City'), (1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City'), (3, 'Mahalaxmi Municipality'), (6, 'Hetauda Sub-metropolitan City'), (4, 'Pokhara Metropolitan City'), (8, 'Tulsipur Municipality'), (9, 'Godawari Municipality'), (10, 'Dhangadi Sub-metropolitan City'), (7, 'Birendranagar Municipality')]
Forbidden (CSRF token missing.): /login/
Forbidden (CSRF token missing.): /login/
Forbidden (CSRF token missing.): /login/
C:\Cosmic\Project\FeedbackAndGrievance\base\models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\utils\deprecation.py", line 122, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Watching for file changes with StatReloader
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(5, 'Dharan Sub-metropolitan City'), (1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City'), (3, 'Mahalaxmi Municipality'), (6, 'Hetauda Sub-metropolitan City'), (4, 'Pokhara Metropolitan City'), (8, 'Tulsipur Municipality'), (9, 'Godawari Municipality'), (10, 'Dhangadi Sub-metropolitan City'), (7, 'Birendranagar Municipality')]
Not Found: /accounts/profile/
Fetched states: ['Koshi Province', 'Madhesh Province', 'Bagmati Province', 'Gandaki Province', 'Lumbini Province', 'Sudurpaschim Province', 'Karnali Province']
Municipalities: [(5, 'Dharan Sub-metropolitan City'), (1, 'Kathmandu Metropolitian City'), (2, 'Lalitpur Metropolitian City'), (3, 'Mahalaxmi Municipality'), (6, 'Hetauda Sub-metropolitan City'), (4, 'Pokhara Metropolitan City'), (8, 'Tulsipur Municipality'), (9, 'Godawari Municipality'), (10, 'Dhangadi Sub-metropolitan City'), (7, 'Birendranagar Municipality')]
Fetching departments for municipality ID: 2
Internal Server Error: /municipalities/2/departments/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: base_department_municipalities

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: base_department_municipalities
Fetching departments for municipality ID: 1
Internal Server Error: /municipalities/1/departments/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: base_department_municipalities

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: base_department_municipalities
C:\Cosmic\Project\FeedbackAndGrievance\base\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\api_views.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\api_views.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\api_views.py changed, reloading.
Watching for file changes with StatReloader
Fetching departments for municipality ID: 2
Internal Server Error: /municipalities/2/departments/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: base_department_municipalities

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: base_department_municipalities
Fetching departments for municipality ID: 2
Internal Server Error: /municipalities/2/departments/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: base_department_municipalities

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: base_department_municipalities
C:\Cosmic\Project\FeedbackAndGrievance\base\api_views.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\FnG\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\FnG\settings.py changed, reloading.
Watching for file changes with StatReloader
Fetching departments for municipality ID: 2
Internal Server Error: /municipalities/2/departments/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: base_department_municipalities

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: base_department_municipalities
C:\Cosmic\Project\FeedbackAndGrievance\base\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\migrations\0004_remove_department_municipality_and_more.py changed, reloading.
Watching for file changes with StatReloader
Fetching departments for municipality ID: 2
Municipality with ID 2 does not exist
Not Found: /municipalities/2/departments/
Fetching departments for municipality ID: 1
Municipality with ID 1 does not exist
Not Found: /municipalities/1/departments/
Fetched states: ['Bagmati']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Not Found: /accounts/profile/
Fetched states: ['Bagmati']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Fetching departments for municipality ID: 1
Fetched states: ['Bagmati']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Fetching departments for municipality ID: 2
Fetched states: ['Bagmati']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Forbidden (CSRF token from POST incorrect.): /logout/
Not Found: /l
Fetched states: ['Bagmati']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Fetching departments for municipality ID: 2
Fetched states: ['Bagmati']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Fetched states: ['Bagmati']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Not Found: /accounts/profile/
Fetched states: ['Bagmati']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Fetching departments for municipality ID: 2
Fetched states: ['Bagmati']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Fetched states: ['Bagmati']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Not Found: /accounts/profile/
Fetched states: ['Bagmati']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Fetching departments for municipality ID: 1
Fetched states: ['Bagmati']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
C:\Cosmic\Project\FeedbackAndGrievance\base\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\views.py changed, reloading.
Watching for file changes with StatReloader
Fetched states: ['Bagmati']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Fetching departments for municipality ID: 1
Fetched states: ['Bagmati']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Fetching departments for municipality ID: 3
Internal Server Error: /municipalities/3/departments/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'feedback_create' with keyword arguments '{'municipality_id': 3, 'pk': 1}' not found. 1 pattern(s) tried: ['departments/(?P<pk>[0-9]+)/feedback/\\Z']
Fetching departments for municipality ID: 1
Internal Server Error: /municipalities/1/departments/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'feedback_create' with keyword arguments '{'municipality_id': 1, 'pk': 1}' not found. 1 pattern(s) tried: ['departments/(?P<pk>[0-9]+)/feedback/\\Z']
Fetched states: ['Bagmati']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Fetched states: ['Bagmati', 'Gandaki', 'Karnali']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Not Found: /accounts/profile/
Fetched states: ['Bagmati', 'Gandaki', 'Karnali']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Grievances fetched for user Reman: []
Fetched states: ['Bagmati', 'Gandaki', 'Karnali']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Fetching departments for municipality ID: 1
Fetched states: ['Bagmati', 'Gandaki', 'Karnali']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Fetched states: ['Bagmati', 'Gandaki', 'Karnali']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Not Found: /accounts/profile/
Fetched states: ['Bagmati', 'Gandaki', 'Karnali']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Fetching departments for municipality ID: 1
Internal Server Error: /municipalities/1/departments/
Traceback (most recent call last):
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Cosmic\Project\FeedbackAndGrievance\env\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'feedback_create' with keyword arguments '{'municipality_id': 1, 'pk': 1}' not found. 1 pattern(s) tried: ['departments/(?P<pk>[0-9]+)/feedback/\\Z']
Watching for file changes with StatReloader
Fetched states: ['Bagmati', 'Gandaki', 'Karnali']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Fetched states: ['Bagmati', 'Gandaki', 'Karnali']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Not Found: /accounts/profile/
Fetched states: ['Bagmati', 'Gandaki', 'Karnali']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Fetching departments for municipality ID: 1
Fetched states: ['Bagmati', 'Gandaki', 'Karnali']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Grievances fetched for user Reman: []
Fetched states: ['Bagmati', 'Gandaki', 'Karnali']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Fetched states: ['Bagmati', 'Gandaki', 'Karnali']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Not Found: /favicon.ico
Fetched states: ['Bagmati', 'Gandaki', 'Karnali']
Municipalities: [(1, 'Kathmandu'), (2, 'Lalitpur'), (3, 'Mahalaxmi')]
Watching for file changes with StatReloader
Not Found: /
Watching for file changes with StatReloader
Not Found: /
Not Found: /favicon.ico
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
Not Found: /
C:\Cosmic\Project\FeedbackAndGrievance\FnG\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\serializers.py changed, reloading.
Watching for file changes with StatReloader
Starting new HTTPS connection (1): raw.githubusercontent.com:443
https://raw.githubusercontent.com:443 "GET /bimalstha23/Nepal-Address-API/main/data/provinces.json HTTP/1.1" 200 112
Starting new HTTPS connection (1): raw.githubusercontent.com:443
https://raw.githubusercontent.com:443 "GET /bimalstha23/Nepal-Address-API/main/data/districts/bagmati.json HTTP/1.1" 404 14
Not Found: /api/municipality
Not Found: /favicon.ico
Not Found: /api/provinces/
Not Found: /favicon.ico
Not Found: /api/provinces/
Not Found: /
Watching for file changes with StatReloader
Not Found: /
Not Found: /favicon.ico
Not Found: /api/provinces
Not Found: /api/municipalities/
Not Found: /favicon.ico
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Cosmic\Project\FeedbackAndGrievance\base\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
Not Found: /favicon.ico
Not Found: /api/municipality/
Not Found: /api/municipality
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Starting new HTTPS connection (1): raw.githubusercontent.com:443
https://raw.githubusercontent.com:443 "GET /bimalstha23/Nepal-Address-API/main/data/provinces.json HTTP/1.1" 200 112
Starting new HTTPS connection (1): raw.githubusercontent.com:443
https://raw.githubusercontent.com:443 "GET /bimalstha23/Nepal-Address-API/main/data/districts/bagmati.json HTTP/1.1" 404 14
Starting new HTTPS connection (1): raw.githubusercontent.com:443
https://raw.githubusercontent.com:443 "GET /bimalstha23/Nepal-Address-API/main/data/districts/sudurpaschim.json HTTP/1.1" 404 14
Starting new HTTPS connection (1): raw.githubusercontent.com:443
https://raw.githubusercontent.com:443 "GET /bimalstha23/Nepal-Address-API/main/data/districts/lumbini.json HTTP/1.1" 404 14
Starting new HTTPS connection (1): raw.githubusercontent.com:443
https://raw.githubusercontent.com:443 "GET /bimalstha23/Nepal-Address-API/main/data/districts/pradesh-1.json HTTP/1.1" 404 14
Starting new HTTPS connection (1): raw.githubusercontent.com:443
https://raw.githubusercontent.com:443 "GET /bimalstha23/Nepal-Address-API/main/data/districts/madhesh.json HTTP/1.1" 404 14
Starting new HTTPS connection (1): raw.githubusercontent.com:443
https://raw.githubusercontent.com:443 "GET /bimalstha23/Nepal-Address-API/main/data/districts/gandaki.json HTTP/1.1" 404 14
Starting new HTTPS connection (1): raw.githubusercontent.com:443
https://raw.githubusercontent.com:443 "GET /bimalstha23/Nepal-Address-API/main/data/districts/karnali.json HTTP/1.1" 404 14
Not Found: /favicon.ico
C:\Cosmic\Project\FeedbackAndGrievance\base\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
Starting new HTTPS connection (1): raw.githubusercontent.com:443
https://raw.githubusercontent.com:443 "GET /nepalutils/geodata/main/data/provinces.json HTTP/1.1" 404 14
Not Found: /favicon.ico
C:\Cosmic\Project\FeedbackAndGrievance\base\migrations\0005_auto_20250817_2010.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
